export const ProfilePostTypes={
    SET_MODAL_SATATUS:'SET_MODAL_SATATUS',
    SET_POST_IMAGE:'SET_POST_IMAGE',
    SET_POST_UUID:'SET_POST_UUID',
    SET_LIKE_STATUS:'SET_LIKE_STATUS',
    SET_UPLOAD_STATUS:'SET_UPLOAD_STATUS'
    
}